version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
      nodejs: 20
    commands:
      # Upgrade pip
      - python3 -m pip install --upgrade pip
      # Install Python dependencies
      - pip install -r Nandin-Erdene/requirements.txt
      # Install CDK
      - npm install -g aws-cdk@2.156.0

  build:
    commands:
      - cd Nandin-Erdene
      - pwd
      - ls -R lib/lambda_handler
      - npx cdk synth

artifacts:
  base-directory: Nandin-Erdene/cdk.out
  files:
    - '**/*'
