version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - cd Nandin-Erdene
      - pip install -r requirements.txt
      - npm install -g aws-cdk@2.156.0
  build:
    commands:
      - npx cdk synth
artifacts:
  base-directory: Nandin-Erdene/cdk.out
  files:
    - '**/*'
